server:
  port: 8001



eureka:
  instance:
    hostname: MacBook-Pro.local
    appname: april-eureka
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false


spring:
  application:
    name: april-eureka

